### PR TITLE
attempt fixing zip segfault on MacOS

### PR DESCRIPTION
**Pull request by philipp-baumann**
@lgnbhl just a short test because I am on Linux, to test on MacOS CI

### CODE REVIEW

**Comment by philipp-baumann** [comment]
I now tested `utils::unzip()` and `archive::archive_extract()`. The first gracefully fails on MacOS and Win, and the latter just fails on MacOS.

**Comment by philipp-baumann** [comment]
https://swissmacuser.ch/macos-terminal-bash-unzip-zip-file-with-tar/

**Comment by philipp-baumann** [comment]
trying to wrap via {sys} or `system2()` for now.

**Comment by lgnbhl** [comment]
> I now tested `utils::unzip()` and `archive::archive_extract()`. The first gracefully fails on MacOS and Win, and the latter just fails on MacOS.

Great idea! I see that in the {archive} documentation that the {fs} package is used. The error on MacOS could be potentially due to list.files(), as mentionned in https://github.com/lgnbhl/BFS/issues/12#issuecomment-1722297591

**Comment by philipp-baumann** [comment]
I'll close this one, but chip in `tools::R_user_dir()` in a separate PR.

**Pull request closed without merging**
